{
 "title": "SE2 Assignment1 dashboard",
 "time": { "from": "now-5m", "to": "now" },
 "panels": [
  {
   "title": "Disk Write Latency",
   "type": "histogram",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "ebpf_exporter_bio_latency_seconds_bucket{operation=\"write\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Memory Utilization Grafana",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "container_memory_max_usage_bytes{container_label_com_docker_compose_service=\"grafana\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Node CPU Utilization",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "avg by(cpu) (rate(node_cpu_seconds_total[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Conitainer CPU usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 8 },
   "targets": [
    {
     "expr": "container_cpu_usage_seconds_total{container_label_com_docker_compose_service=\"prometheus\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "container_cpu_usage_seconds_total{container_label_com_docker_compose_service=\"grafana\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Transmit and Recieve bytes Promotheus",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 8 },
   "targets": [
    {
     "expr": "container_network_receive_bytes_total{container_label_com_docker_compose_service=\"prometheus\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "container_network_transmit_bytes_total{container_label_com_docker_compose_service=\"prometheus\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "ebpf_exporter syscalls (read & write)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "ebpf_exporter_syscalls_total{syscall=\"read\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "ebpf_exporter_syscalls_total{syscall=\"write\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Nodes Memory Utilization",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 16 },
   "targets": [
    {
     "expr": "node_memory_MemTotal_bytes{instance=\"node_container:9441\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "node_memory_MemAvailable_bytes{instance=\"node_container:9441\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "cache miss on host",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 7, "x": 16, "y": 16 },
   "targets": [
    { "expr": "ebpf_exporter_llc_misses_total", "legendFormat": "__auto" }
   ]
  }
 ]
}